### ISSUE TITLE
awk seems unreliable

### ISSUE THREAD

**Issue by hausmanconsulting** [dtypo/Home-Mode-Switcher-for-Synology-Surveillance-Station#4]
I understand the desire to keep this solution limited to shell scripting, but the usage of awk seems problematic. When I run this script against my SS installation, the homestate_prev_syno line returns "2".

This appears to be from this segment on line 60:

`|awk -F',' '{ print $124 }'|awk -F':' '{ print $2 }')`

$124 lands in the middle of notify_event_list in the JSON output. I think a more robust solution will be to parse the JSON itself looking for the return value that is expected (my guess is the result of the "on" value given that the API call references "HomeMode"). I will fork this and make edits but it will most likely use PHP to parse and deal with JSON.

**Comment by dtypo** [comment]
Replaced the AWK call with native bash string manipulation.
Please update the script! :)
